export const TRANSACTIONS_TRANSACTIONS_SETTER =
  "TRANSACTIONS_TRANSACTIONS_SETTER";
export const TRANSACTIONS_GET_TRANSACTIONS = "TRANSACTIONS_GET_TRANSACTIONS";
export const TRANSACTIONS_RESET_STATE = "TRANSACTIONS_RESET_STATE";
