export const AUTH_ISLOGGEDIN_SETTER = "AUTH_ISLOGGEDIN_SETTER";
export const AUTH_LOGGEDUSEREMAIL_SETTER = "AUTH_LOGGEDUSEREMAIL_SETTER";
export const AUTH_EMAIL_SETTER = "AUTH_EMAIL_SETTER";
export const AUTH_EMAIL_ERROR_SETTER = "AUTH_EMAIL_ERROR_SETTER";
export const AUTH_PASSWORD_SETTER = "AUTH_PASSWORD_SETTER";
export const AUTH_PASSWORD_ERROR_SETTER = "AUTH_PASSWORD_ERROR_SETTER";

export const AUTH_LOGIN_SIGNUP = "AUTH_LOGIN_SIGNUP";
export const AUTH_REQUESTED = "AUTH_REQUESTED";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CHECKIFLOGGEDIN = "CHECKIFLOGGEDIN";
export const AUTH_RESET_STATE = "AUTH_RESET_STATE";
