export const PRODUCTS_PRODUCTS_SETTER = "PRODUCTS_PRODUCTS_SETTER";
export const PRODUCTS_CATEGORY_SETTER = "PRODUCTS_CATEGORY_SETTER";
export const PRODUCTS_GET = "PRODUCTS_GET";
export const PRODUCTS_GET_SUCCESS = "PRODUCTS_GET_SUCCESS";
export const PRODUCTS_GET_FAILURE = "PRODUCTS_GET_FAILURE";
export const PRODUCTS_RESET_STATE = "PRODUCTS_RESET_STATE";
