export const CATEGORIES_CATEGORIES_SETTER = "CATEGORIES_CATEGORIES_SETTER";
export const CATEGORIES_ISLOADING_SETTER = "CATEGORIES_ISLOADING_SETTER";
export const CATEGORIES_GET = "CATEGORIES_GET";
export const CATEGORIES_GET_REQUESTED = "CATEGORIES_GET_REQUESTED";
export const CATEGORIES_GET_SUCCESS = "CATEGORIES_GET_SUCCESS";
export const CATEGORIES_GET_FAILURE = "CATEGORIES_GET_FAILURE";
