export const CART_GET_DISCOUNTS = "CART_GET_DISCOUNTS";
export const CART_DISCOUNTS_SETTER = "CART_DISCOUNTS_SETTER";
export const CART_ISDISCOUNTAPPLIED_SETTER = "CART_ISDISCOUNTAPPLIED_SETTER";
export const CART_PRODUCTS_SETTER = "CART_PRODUCTS_SETTER";
export const CART_TOTALPRICE_BEFORE_DISCOUNT_SETTER =
  "CART_TOTALPRICE_BEFORE_DISCOUNT_SETTER";
export const CART_TOTALPRICE_AFTER_DISCOUNT_SETTER =
  "CART_TOTALPRICE_AFTER_DISCOUNT_SETTER";
export const CART_ADD_REMOVE_PRODUCT = "CART_ADD_REMOVE_PRODUCT";
export const CART_SEND_TRANSACTION = "CART_SEND_TRANSACTION";
export const CART_SEND_TRANSACTION_SUCCESS = "CART_SEND_TRANSACTION_SUCCESS";
export const CART_SEND_TRANSACTION_FAILURE = "CART_SEND_TRANSACTION_FAILURE";
export const CART_CLEAR_CART = "CART_CLEAR_CART";
export const CART_RESET_STATE = "CART_RESET_STATE";
