export const PAGINATION_INCREMENT = "PAGINATION_INCREMENT";
export const PAGINATION_DECREMENT = "PAGINATION_DECREMENT";
export const PAGINATION_NEW_STATE = "PAGINATION_NEW_STATE";
export const PAGINATION_RESET_STATE = "PAGINATION_RESET_STATE";
export const UNCHANGED = "UNCHANGED";
